version: '2'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: teracy/hello-world-nodejs:dev_develop
    command: bash -c "npm run start:dev"
    volumes:
      - .:/opt/app
    ports:
      - 3000
    restart: always
    # nginx-proxy
    environment:
      - VIRTUAL_HOST=hello-d.teracy.dev
    # to get this work with https://github.com/jwilder/nginx-proxy
    # related: https://github.com/jwilder/nginx-proxy/issues/305
    network_mode: bridge
